# Generated by Django 5.0.2 on 2024-03-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Уведомления на почту'),
        ),
    ]
