# Generated by Django 5.0.2 on 2024-05-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_keys',
            field=models.IntegerField(default=0, verbose_name='Количество ключей'),
        ),
    ]
