# Generated by Django 5.0.2 on 2024-04-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0004_rename_api_type_instructions_api_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='category_images', verbose_name='Логотип сервиса')),
                ('summary', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Краткая информация')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Инструкция')),
                ('realization', models.URLField(blank=True, max_length=300, null=True, verbose_name='Графическая реализация')),
                ('original', models.URLField(blank=True, max_length=300, null=True, verbose_name='Оригинальная документация')),
                ('github', models.URLField(blank=True, max_length=100, null=True, verbose_name='Ссылка на ваш github')),
                ('api_type', models.CharField(choices=[('paid', 'платный'), ('free', 'бесплатный')], default='paid', max_length=4, verbose_name='Тип API')),
                ('categories', models.ManyToManyField(default=None, to='category.categories', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'New_API',
                'verbose_name_plural': 'Новые API',
                'db_table': 'new_api',
                'ordering': ('id',),
            },
        ),
    ]
