# Generated by Django 5.0.2 on 2024-05-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_services', '0002_newapi_user_alter_newapi_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newapi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
    ]
