# Generated by Django 5.0.2 on 2024-05-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_services', '0003_newapi_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newapi',
            name='logo_svg',
            field=models.FileField(blank=True, null=True, upload_to='category_images', verbose_name='Логотип сервиса'),
        ),
    ]
