# Generated by Django 5.0.2 on 2024-05-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_services', '0004_newapi_logo_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='newapi',
            name='status',
            field=models.CharField(choices=[('Проверяется', 'Проверяется'), ('Проверено', 'Проверено'), ('Отклонено', 'Отклонено')], default='Проверяется', max_length=11),
        ),
    ]
