# Generated by Django 5.0.2 on 2024-05-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_services', '0005_newapi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newapi',
            name='status',
            field=models.CharField(choices=[('being_checked', 'Проверяется'), ('accepted', 'Проверено'), ('rejected', 'Отклонено')], default='being_checked', max_length=13),
        ),
    ]
