# Generated by Django 5.0.2 on 2024-03-03 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=75, null=True, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='category_images', verbose_name='Логотип сервиса')),
                ('summary', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Краткая информация')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Инструкция')),
                ('date', models.DateField(auto_now=True, verbose_name='Последнее изменение')),
                ('realization', models.URLField(blank=True, max_length=300, null=True, verbose_name='Графическая реализация')),
                ('original', models.URLField(blank=True, max_length=300, null=True, verbose_name='Оригинальная документация')),
                ('API_type', models.CharField(choices=[('paid', 'платный'), ('free', 'бесплатный')], default='paid', max_length=4, verbose_name='Тип API')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='category.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'API',
                'verbose_name_plural': 'API сервисы',
                'db_table': 'instructions',
                'ordering': ('id',),
            },
        ),
    ]
