# Generated by Django 5.0.2 on 2024-03-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_instructions_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructions',
            name='categories',
            field=models.ManyToManyField(default=None, to='category.categories', verbose_name='Категории'),
        ),
    ]
