# Generated by Django 5.0.2 on 2024-04-01 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_instructions_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructions',
            old_name='API_type',
            new_name='api_type',
        ),
    ]
