# Generated by Django 5.0.2 on 2024-05-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_categories_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Иконка'),
        ),
    ]
